{
  homeInputs,
  pkgs,
  ...
}:
{
  imports = [
    ./kitty.nix
    ./minecraft.nix
    ./firefox.nix
    ./spotify.nix
    ./virt-manager.nix
    ./ghostty.nix
    ./ee2.nix
    ./poetrade.nix
    ./recording.nix
    ./foot.nix
    ./alacritty.nix
    ./mpv.nix
    ./zen.nix
    ./lg.nix
    ./eza.nix
    ./zoxide.nix
    ./ripgrep.nix
    ./fish.nix
    ./fzf.nix
    ./git.nix
    ./ssh.nix
    ./devenv.nix
    ./nettools.nix
  ];

  home.packages = with pkgs; [
    homeInputs.nvim-flake.packages.${pkgs.stdenv.hostPlatform.system}.default
    jq
    htop
    fd
    tldr
    rsync
    ncdu
    tmux
    just
    nvtopPackages.full
    pciutils
    usbutils
    inetutils
    cryptsetup
    gptfdisk
  ];
}
